version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: ${DOCKER_IMAGE}
    volumes:
      - '.:/app'
    ports:
      - '${DOCKER_APP_PORT-3000}:3000'
