services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: ${DOCKER_IMAGE}
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - 'node_modules:/app/node_modules'
      - type: volume
        source: node_modules
        target: /data
        volume:
          nocopy: true
    ports:
      - '${DOCKER_APP_PORT-3000}:3000'
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_PATH_MOUNT_NODE_MODULE_DATA}
